### ISSUE TITLE
[Feat]: Asset folders

### ISSUE THREAD

**Issue by tommerty** [dorasto/public#25]
### What are you looking for?

Asset folders to organize your assets
One level deep, not building an entire file system. We can literally just assign them to accordion or popover IDs

**Comment by tommerty** [comment]
Almost done. Just need to make the Input be a selector, similar to post category

![Image](https://github.com/user-attachments/assets/75f5c82b-8dc8-4493-9d76-e79918358802)

**Comment by wogozyt** [comment]
Oh yeah! Another banger and awaited feature!

**Comment by tommerty** [comment]
https://github.com/user-attachments/assets/c6c065c0-91cd-44fe-850e-50bc7c373772

Big progress, just need to finish up the search and selector
