### ISSUE TITLE
Doras domain - BSky usernames

### ISSUE THREAD

**Issue by tommerty** [dorasto/public#47]
### Doras Username

tommerty

### What are you looking for?

@trent-001 has been cooking on an idea to allow any user on Doras to use their Doras username as their bluesky username, and has been requested on the Discord: https://discord.com/channels/1172459860114284564/1296649890595868763

Trent believes this is possible quite easily, and hoping to have it done in a future release

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.

**Comment by trent-001** [comment]
https://github.com/dorasto/doras/pull/541
