### ISSUE TITLE
Uploading pictures from any block

### ISSUE THREAD

**Issue by wogozyt** [dorasto/public#48]
### Doras Username

wogozyt

### What are you looking for?

It would be cool if we could upload pictures from any blocks that you can use assets like link block, image, image carousel and so on, cheers

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.

**Comment by tommerty** [comment]
@trent-001 so this is similar to how now on image block you can upload images directly, it's just not available on all things like carousel etc.

**Comment by trent-001** [comment]
**New Asset Gallery Component**
- [x] Image Block
- [x] Carousel Block
- [x] Rich Text / Blog post
- [x] blog banner image
- [x] background for profile

@tommerty anything missing?

**Comment by wogozyt** [comment]
Link & Multilink (icon picker), I think we have added to everything
