### ISSUE TITLE
Public Asset Gallery

### ISSUE THREAD

**Issue by tommerty** [dorasto/public#54]
### Doras Username

tommerty

### What are you looking for?

Public asset gallery of all Doras icons for marketing etc

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.

**Comment by tommerty** [comment]
Done and already released: https://doras.to/posts?blog=official-assets.

In v0.3.2 this will be linked in the command center
