### ISSUE TITLE
🐞 - blogging limit locks user from editing blogs

### ISSUE THREAD

**Issue by WillLuminate** [dorasto/public#60]
### What happened?

blogging issue - free users locked out of blog editing when 5 blogs are on profile. should be able to edit cycle blogs 

### Replication Steps

have 5 blogs on a free account and try edit

### User or Brand related

On a brand account

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.

**Comment by tommerty** [comment]
Resolved
