### ISSUE TITLE
Improved Analytics

### ISSUE THREAD

**Issue by tommerty** [dorasto/public#63]
### Doras Username

tommerty

### What are you looking for?

Improved Analytics

![Image](https://github.com/user-attachments/assets/b5b6a407-14a8-4fa6-84c3-8e18b1bf397d)
![Image](https://github.com/user-attachments/assets/b0940c2b-8a41-495e-aca8-bd3acbccdfd1)
![Image](https://github.com/user-attachments/assets/f1c8584a-2cf5-4442-8b28-4a8c6a08f27f)

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.
