### ISSUE TITLE
Command Center - URL Parameters

### ISSUE THREAD

**Issue by tommerty** [dorasto/public#64]
### Doras Username

tommerty

### What are you looking for?

Have the command center include query parameters for easier navigation

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.

**Comment by tommerty** [comment]
![Image](https://github.com/user-attachments/assets/a428f345-f1c5-467e-9350-198acda801c4)
