### ISSUE TITLE
🐞 - Blogging fixes

### ISSUE THREAD

**Issue by tommerty** [dorasto/public#65]
### Doras Username

tommerty

### What happened?

Columns were a mess, and things weren't clear

### User or Brand related

My acconut

### What browsers are you seeing the problem on?

Firefox, Chrome (or chrome based like Brave, Arc, etc), Safari

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.

**Comment by tommerty** [comment]
- Blocknote is updated to 0.21.0 from 0.19.2: https://github.com/TypeCellOS/BlockNote/releases

**Comment by tommerty** [comment]
Fixed a bug where the Back button only appeared on brand blog posts

![Image](https://github.com/user-attachments/assets/1be84c87-a3cb-4ba6-93a0-37240a9957b4)

**Comment by tommerty** [comment]
Added back the "leading block" when on edit mode (always creates an empty line below)

https://github.com/user-attachments/assets/4c67d8f1-390e-4da0-958c-c79a751dfdc2


Only happens on edit mode to stop an empty line being rendered
