### ISSUE TITLE
🐞 - Mobile improvements

### ISSUE THREAD

**Issue by tommerty** [dorasto/public#66]
### Doras Username

Tommerty

### What happened?

Navigating on mobile right now has some bugs:

- Navigation sheet doesn't open
- Odd spacing
- Content getting squashed

### Replication Steps

Literally anything on mobile admin dashboard

### User or Brand related

My acconut

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.

**Comment by tommerty** [comment]
improved top navigation when it's needed/called

![Image](https://github.com/user-attachments/assets/bf6bedba-5d1d-4fb0-9d14-16ec229172ed)

**Comment by tommerty** [comment]
Help visualize that it can scroll
![Image](https://github.com/user-attachments/assets/f2fe28fe-a96f-420e-82a4-b37bb13644a5)

**Comment by tommerty** [comment]
Link shortening mobile view

![Image](https://github.com/user-attachments/assets/1c47604b-8445-4a8a-b06c-361293985214)

**Comment by tommerty** [comment]
![Image](https://github.com/user-attachments/assets/bae6c4a7-edc2-49ca-a168-5e4db07c1d65)
