### ISSUE TITLE
Brand homepage improvements

### ISSUE THREAD

**Issue by tommerty** [dorasto/public#67]
### Doras Username

tommerty

### What are you looking for?

Brand homepage is ass, needs some TLC

**Comment by doras-to-admin** [comment]
**Thank you for making Doras a better place 🚀**

  This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.

**Comment by tommerty** [comment]
![Image](https://github.com/user-attachments/assets/3bead40a-8bf7-4fe6-b1c7-21dcd9180124)
